---
title: "ENV 790.30 - Time Series Analysis for Energy Data | Spring 2024"
subtitle: "Assignment 1 - Due date 01/18/24"
author: "Shubhangi Gupta"
output: pdf_document
geometry: margin=2.54cm
---

## Directions

Before making any edits to this file, please rename it such that it includes your first and last name (e.g., "LuanaLima_TSA_A01_Sp24.Rmd")

Once you have this renamed file open in RStudio, the first thing you will do is replace "Student Name" on line 3 with your name. 
Then you will start working through the assignment by  **creating code and output** that answer each question. Be sure to use this assignment document. Your report should contain the answer to each question and any plots/tables you obtained (when applicable).

When you have completed the assignment, **Knit** the text and code into a single PDF file.  Submit this pdf using Sakai. 

## Questions

Q1. What are your previous experiences with time series analysis, R, and Git? 

> Answer: I did my Bachelor’s in Statistics and learnt a basic level of R as a part of my degree. However, it has been 5 years since I graduated and don't remember much R anymore! I did, however, use Github during our Energy Modeling class last semester, and am simultaneously pursuing power modeling and Environmental Data Analytics this semester. My experience with Time Series Analysis lies in my work at my previous job as a Climate Policy Researcher at an environmental think tank (World Resources Institute India) where I used an energy-economy model to make long-term low-carbon pathways for India. All the model outputs were time series data since the pathways extended from 2020-2050 and my role was to (1) clean the data and make it usable in the form of tables and charts and (2) analyse the trends in the data to make policy recommendations. During this project, I used excel and very basic trend analysis and so, in this class, I hope to learn more robust tools to be able to forecast and analyse such pathways and do such work in a more robust manner on a more sophisticated software than Excel.


Q2. (Only if you choose to use git) Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file as instructed on the recorded video "Getting started with Git and Github". 

> Answer: https://github.com/shubhangi-gupta-54/TSA_Sp24


Q3. For this part we just want to see the path to your R project. No need to do anything. The output will be automatically generated once you knit you file. 

> Answer: This is my working directory:

```{r}
getwd()
````


